"""Add templateId to Wbs model

Revision ID: 950d1784f10c
Revises: 
Create Date: 2024-10-15 02:02:19.976878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950d1784f10c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('activities', sa.Column('activityID', sa.Integer(), nullable=False))
    # op.drop_index('ix_activities_activityId', table_name='activities')
    # op.create_index(op.f('ix_activities_activityID'), 'activities', ['activityID'], unique=False)
    # op.drop_constraint(None, 'activities', type_='foreignkey')
    # op.create_foreign_key(None, 'activities', 'templates', ['templateId'], ['templateId'])
    # op.create_foreign_key(None, 'activities', 'activities', ['parentActivityId'], ['activityID'])
    # op.drop_column('activities', 'activityId')
    # op.add_column('wbs', sa.Column('templateId', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'wbs', 'templates', ['templateId'], ['templateId'])
    # ### end Alembic commands ###
    op.add_column('wbs', sa.Column('templateId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wbs', 'templates', ['templateId'], ['templateId'])
    
    # Add foreign key for templateId in activities table if it doesn't exist
    op.create_foreign_key(None, 'activities', 'templates', ['templateId'], ['templateId'])




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the foreign keys and the templateId column
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'wbs', type_='foreignkey')
    op.drop_column('wbs', 'templateId')
    # ### end Alembic commands ###
